# Configuration MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port de l'application
server.port=${SERVER_PORT}

# JWT Configuration
nhcwash.app.jwtSecret=${JWT_SECRET}
nhcwash.app.jwtExpirationMs=${JWT_EXPIRATION}